sudo: false
language: node_js
services:
  - postgresql
cache:
  directories:
  - node_modules
node_js:
  - "6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rm -rf ./coverage
script:
  - npm run cov