sudo: false
language: node_js
services:
  - postgresql
cache:
  directories:
  - node_modules
node_js:
  - "6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rm -rf ./coverage
install:
  - npm i -g codecov
script:
  - NODE_ENV=travis yarn run cov
  - codecov