sudo: false
language: node_js
services:
  - postgresql
node_js:
  - "6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - rm -rf ./coverage
  - npm i
install:
  - npm i -g codecov
script:
  - NODE_ENV=travis DEBUG=pglize* ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec ./tests/*.spec.js
  - codecov
